# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/ece.cmu.edu/usr/suyashb/Private/545/z80IP/z80IP.cache/wt [current_project]
set_property parent.project_path /afs/ece.cmu.edu/usr/suyashb/Private/545/z80IP/z80IP.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
read_verilog /afs/ece.cmu.edu/usr/suyashb/Private/545/z80IP/z80IP.srcs/sources_1/imports/z80/z80_defines.vh
read_verilog -library xil_defaultlib -sv {
  /afs/ece.cmu.edu/usr/suyashb/Private/545/z80IP/z80IP.srcs/sources_1/imports/library/library.sv
  /afs/ece.cmu.edu/usr/suyashb/Private/545/z80IP/z80IP.srcs/sources_1/imports/z80/z80_control.sv
  /afs/ece.cmu.edu/usr/suyashb/Private/545/z80IP/z80IP.srcs/sources_1/imports/z80/z80_datapath.sv
  /afs/ece.cmu.edu/usr/suyashb/Private/545/z80IP/z80IP.srcs/sources_1/imports/z80/z80_top.sv
}
synth_design -top z80 -part xc7z020clg484-1
write_checkpoint -noxdef z80.dcp
catch { report_utilization -file z80_utilization_synth.rpt -pb z80_utilization_synth.pb }
