ocf_fsm:
	vcs -sverilog -debug ../z80_control.sv ocf_fsm_tb.sv ../../library/library.sv

decoder:
	vcs -sverilog -debug ../z80_control.sv decoder_tb.sv ../../library/library.sv

control:
	vcs -sverilog -debug ../z80_control.sv control_tb.sv ../../library/library.sv
